[package]
name = "handle_test_checker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glib = "0.15"
gdk = "0.15"
gio = "0.15"

[dependencies.gtk]
version = "0.15"
features = ["v3_24"]
